// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919092330_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Exams.ExamTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("ExamTemplates");
                });

            modelBuilder.Entity("Api.Models.Exams.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ExamTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamTemplateId");

                    b.ToTable("QuestionTemplates");

                    b.HasDiscriminator<int>("QuestionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Models.Exams.LongAnswerQuestionTemplate", b =>
                {
                    b.HasBaseType("Api.Models.Exams.QuestionTemplate");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Api.Models.Exams.MultipleChoiceQuestionTemplate", b =>
                {
                    b.HasBaseType("Api.Models.Exams.QuestionTemplate");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("AnswerOptions");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Api.Models.Exams.ShortAnswerQuestionTemplate", b =>
                {
                    b.HasBaseType("Api.Models.Exams.QuestionTemplate");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Api.Models.Exams.SingleChoiceQuestionTemplate", b =>
                {
                    b.HasBaseType("Api.Models.Exams.QuestionTemplate");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("AnswerOptions");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Api.Models.Exams.ExamTemplate", b =>
                {
                    b.HasOne("Api.Models.Identity.User", "CreatedBy")
                        .WithMany("ExamTemplates")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Api.Models.Exams.QuestionTemplate", b =>
                {
                    b.HasOne("Api.Models.Exams.ExamTemplate", "ExamTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("ExamTemplateId");

                    b.Navigation("ExamTemplate");
                });

            modelBuilder.Entity("Api.Models.Exams.ExamTemplate", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Api.Models.Identity.User", b =>
                {
                    b.Navigation("ExamTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
